### PR TITLE
Jenkinsfile.journal-cms-restore-continuumtest, threadbare backend

### PR DESCRIPTION
**Pull request by lsh-0**
re-enables threadbare backend

### CODE REVIEW

**Comment by lsh-0** [comment]
We'll soon find out if it works.

**Comment by lsh-0** [comment]
it was run today, but not by me. Does it run if there is an update?

It failed with an error in the restore script I figured out in some other ticket:

> /ext/tmp/20200423_prod--journal-cms.elifesciences.org_002525-archive-b47198f6.tar.gz\n/ext/tmp/20200426_prod--journal-cms.elifesciences.org_002401-archive-b47198f6.tar.gz: Cannot open: No such file or directory

it doesn't handle leftover files very well.

I'll clean it up and give it a manual start now just to be sure the threadbare backend change is in.

The threadbare changes are [unfortunately failing in builder right now](https://github.com/elifesciences/builder/pull/655) with what looks like a timeout issue which I need to investigate separately. I can't imagine what it is

**Comment by lsh-0** [comment]
The db was restored without issue but I can't verify that Jenkins was using the updated script with the threadbare backend enabled.

**Comment by giorgiosironi** [comment]
It runs [every Monday](https://alfred.elifesciences.org/job/process/job/process-journal-cms-restore-continuumtest/configure).

**Comment by lsh-0** [comment]
I'm still seeing these in the script output:

```
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
```

how do I confirm that Jenkins is using the updated script that uses threadbare?

**Pull request merged**
